---
- name: NXOS Ansible test connection
  hosts: nxos
  
  tasks:
    - name: run show version on remote devices
      nxos_command:
        commands: show version
        wait_for: result[0] contains Cisco
